const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Plugins.Keyboard,
		C3.Behaviors.Follow,
		C3.Plugins.Text,
		C3.Behaviors.LOS,
		C3.Behaviors.EightDir,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Turret,
		C3.Behaviors.Bullet,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Behaviors.Turret.Acts.SetPredictiveAim,
		C3.Behaviors.Turret.Acts.SetRateOfFire,
		C3.Behaviors.Turret.Cnds.OnShoot
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{DesplazarHasta: 0},
	{Jugador: 0},
	{Sólido: 0},
	{SaltoATravés: 0},
	{FondoEnMosaico: 0},
	{Tomate: 0},
	{Teclado: 0},
	{Seguir: 0},
	{npc: 0},
	{Sprite2: 0},
	{Texto: 0},
	{FondoEnMosaico2: 0},
	{Sprite: 0},
	{LíneaDeVisión: 0},
	{"8Direcciones": 0},
	{MoverA: 0},
	{Torreta: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{FondoEnMosaico3: 0},
	{FondoEnMosaico4: 0},
	{Bala: 0},
	{Sprite7: 0},
	{Sprite8: 0}
];

self.InstanceType = {
	Jugador: class extends self.ISpriteInstance {},
	FondoEnMosaico: class extends self.ITiledBackgroundInstance {},
	Tomate: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	npc: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	FondoEnMosaico2: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	FondoEnMosaico3: class extends self.ITiledBackgroundInstance {},
	FondoEnMosaico4: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {}
}